"""Deterministic risk provider backed by synthetic ML artifacts.

This provider reads the static JSON artifact generated by the synthetic ML research
repository. It acts as an adapter, mapping the pre-computed synthetic monitoring
evaluations and LLM explanations into the application's native RiskAssessment contract.

The provider deterministically matches the application's demo trajectories to the
pre-generated cases in the artifact to ensure the frontend can predictably demonstrate
stable, deterioration, and adverse event scenarios without live ML inference.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from .provider import RiskProvider
from ..schema.monitoring_enums import RiskLevel, MeasurementType
from ..schema.monitoring_result import (
    ContributingFactor,
    PatientState,
    RiskAssessment,
)

ARTIFACT_PATH = Path(__file__).parent.parent / "synthetic" / "artifacts" / "synthetic_demo_cases.json"

class SyntheticArtifactProvider(RiskProvider):
    name: str = "synthetic"
    version: str = "isolation_forest_c0.10"

    def __init__(self):
        self._cases = {}
        self._load_artifact()

    def _load_artifact(self):
        try:
            with open(ARTIFACT_PATH) as f:
                cases = json.load(f)
            
            # Index by the original synthetic ground truth scenario (e.g. STABLE, SUDDEN_DETERIORATION)
            for case in cases:
                scenario = case.get("ground_truth_scenario")
                if scenario:
                    self._cases[scenario] = case
        except Exception as e:
            # If the artifact is missing or malformed, the provider degrades safely.
            print(f"Warning: Failed to load synthetic artifacts from {ARTIFACT_PATH}: {e}")

    def assess(self, state: PatientState, now: datetime) -> RiskAssessment:
        # Determine the demo trajectory of this patient to select the correct case.
        # The demo generator in the application creates predictable patient IDs like "PT-demo-SUDDEN_DETERIORATION".
        scenario = None
        for key in ["STABLE", "SUDDEN_DETERIORATION", "ADVERSE_EVENT", "GRADUAL_DETERIORATION", "IMPROVING", "RECOVERY", "NOISY_SENSOR"]:
            if key in state.patient_id:
                scenario = key
                break
        
        # If the case isn't in our artifact, fallback to degraded.
        case = self._cases.get(scenario)
        if not case:
            return self._degraded(state, now)
        
        det_exp = case.get("deterministic_explanation", {})
        gemini = case.get("gemini_explanation")
        
        # 1. Status -> RiskLevel
        status = det_exp.get("status", "normal")
        level = RiskLevel.RED if status == "anomaly" else RiskLevel.GREEN
        if status == "data_gap":
            level = RiskLevel.UNKNOWN
            
        # 2. Score
        score = det_exp.get("anomaly_score")
        if score is None:
            score = 0.0
            
        # 3. Contributing factors (Deterministic Evidence)
        factors = []
        ev_signals = case.get("physiological_evidence", {})
        directions = det_exp.get("direction", [])
        
        # Best effort mapping of directions to MeasurementType
        # "HEART_RATE increasing" -> MeasurementType.HEART_RATE
        for d in directions:
            parts = d.split()
            if len(parts) >= 2:
                sig_name = parts[0]
                direction = parts[1]
                m_type = None
                if sig_name == "HEART_RATE":
                    m_type = MeasurementType.HEART_RATE
                elif sig_name == "SPO2":
                    m_type = MeasurementType.SPO2
                elif sig_name == "RESPIRATORY_RATE":
                    m_type = MeasurementType.RESPIRATORY_RATE
                
                factors.append(
                    ContributingFactor(
                        factor="physiological anomaly detected",
                        detail=f"Observed physiological change: {d}",
                        weight=1.0,
                        measurement_type=m_type
                    )
                )

        # 4. Likely Patterns (Gemini or Deterministic)
        patterns = []
        if gemini:
            patterns.append(gemini.get("summary", ""))
            patterns.extend(gemini.get("key_findings", []))
            patterns.append(gemini.get("caveats", ""))
        else:
            patterns.append(det_exp.get("evidence_summary", "No summary available."))
            
        # Ensure provenance is clear
        patterns.append(f"[Source: {self.name} | Version: {self.version}]")

        return RiskAssessment(
            assessment_id=f"risk-synthetic-{state.patient_id}-{now.timestamp()}",
            patient_id=state.patient_id,
            trial_id=state.trial_id,
            assessed_at=now,
            level=level,
            score=min(max(score, 0.0), 1.0),
            confidence=1.0,
            prediction_horizon_hours=1,
            contributing_factors=factors,
            likely_patterns=[p for p in patterns if p],
            provider=self.name,
            model_version=self.version,
            degraded=False
        )

    def _degraded(self, state: PatientState, now: datetime) -> RiskAssessment:
        return RiskAssessment(
            assessment_id=f"risk-degraded-{state.patient_id}-{now.timestamp()}",
            patient_id=state.patient_id,
            trial_id=state.trial_id,
            assessed_at=now,
            level=RiskLevel.UNKNOWN,
            score=0.0,
            confidence=0.0,
            prediction_horizon_hours=0,
            contributing_factors=[],
            likely_patterns=["Synthetic artifact missing or unmatched trajectory"],
            provider=self.name,
            model_version=self.version,
            degraded=True
        )
