"""M9/M12: the Phase 2 vertical slice, end to end.

The critical integration test proves the whole chain on real components — no
stubs beyond the deterministic risk provider that Phase 2 actually ships:

    ELIGIBLE screening
      -> treatment registered
      -> observations ingested
      -> patient state updated
      -> risk generated
      -> trust gate applied
      -> intervention generated
      -> next-dose decision generated

and that Phase 1 still behaves identically alongside it.
"""

from datetime import datetime, timezone

import pytest

from app.fixtures_loader import load_patient, load_trial
from app.monitoring.ingestion import ObservationIngestionService
from app.monitoring.service import MonitoringService
from app.monitoring.treatment import TreatmentService
from app.repository.json_monitoring import JsonMonitoringRepository
from app.repository.json_repo import JsonRepository
from app.schema.enums import OverallStatus
from app.schema.monitoring_enums import (
    InterventionAction,
    MonitoringEventType,
    NextDoseDecision,
    RiskLevel,
)
from app.service import ScreeningService
from app.synthetic.generator import Trajectory, generate_windowed

# Trial ids come from the fixtures, never hardcoded here: patient_eligible is
# screened against trial_supported (CT-002), while the PDF demo record uses
# trial_demo (CT-001). Every helper below takes the trial id from the treatment
# that was actually registered.
START = datetime(2026, 8, 16, 6, 0, tzinfo=timezone.utc)


@pytest.fixture
def rig(tmp_path):
    screening_repo = JsonRepository(tmp_path / "store.json")
    monitoring_repo = JsonMonitoringRepository(tmp_path / "monitoring.json")
    return {
        "screening": ScreeningService(repository=screening_repo),
        "treatment": TreatmentService(screening_repo, monitoring_repo),
        "ingestion": ObservationIngestionService(monitoring_repo),
        "monitoring": MonitoringService(monitoring_repo),
        "repo": monitoring_repo,
    }


def _register_eligible(rig):
    """Phase 1 screening through to a registered Phase 2 treatment."""
    screening = rig["screening"].screen(
        load_patient("patient_eligible"), load_trial("trial_supported")
    )
    assert screening.overall_status is OverallStatus.ELIGIBLE

    treatment = rig["treatment"].register(
        screening_result_id=screening.result_id,
        drug_name="Compound X",
        now=START,
    )
    return screening, treatment


def _drive(rig, treatment, trajectory, windows=5, seed=7):
    """Ingest a trajectory window by window, running a cycle after each."""
    patient_id, trial_id = treatment.patient_id, treatment.trial_id
    batches = generate_windowed(
        patient_id, trial_id, trajectory, START, windows=windows, hours=8, seed=seed
    )
    cycles = []
    for batch in batches:
        now = max(o.recorded_at for o in batch)
        rig["ingestion"].ingest(batch, now=now)
        cycles.append(rig["monitoring"].run_cycle(patient_id, trial_id, now))
    return cycles


def _collapse(levels):
    out = []
    for level in levels:
        if not out or out[-1] is not level:
            out.append(level)
    return out


# =========================================================================
# The critical integration test
# =========================================================================


def test_eligible_patient_flows_all_the_way_to_a_next_dose_decision(rig):
    """ELIGIBLE -> treatment -> observations -> state -> risk -> intervention -> next dose."""
    screening, treatment = _register_eligible(rig)
    patient_id = treatment.patient_id

    trial_id = treatment.trial_id
    batch = generate_windowed(
        patient_id, trial_id, Trajectory.STABLE, START, windows=1, hours=4, seed=5
    )[0]
    now = max(o.recorded_at for o in batch)
    ingestion = rig["ingestion"].ingest(batch, now=now)
    assert ingestion.accepted_count > 0

    cycle = rig["monitoring"].run_cycle(patient_id, trial_id, now)

    # 1. Patient state was built from the ingested observations.
    assert cycle.state.observation_count == ingestion.accepted_count
    assert cycle.state.treatment.treatment_id == treatment.treatment_id
    assert cycle.state.measurements

    # 2. Risk was generated by the provider.
    assert cycle.risk.provider == "mock-risk-v1"
    assert cycle.risk.level is RiskLevel.GREEN

    # 3. The trust gate ran and let the verdict through.
    assert cycle.effective_risk.level is RiskLevel.GREEN
    assert cycle.effective_risk.gated is False

    # 4. An intervention came from the protocol table.
    assert cycle.interventions
    assert cycle.interventions[0].protocol_rule_id.startswith("DEMO-")

    # 5. A next-dose decision was reached.
    assert cycle.next_dose is not None
    assert cycle.next_dose.decision is NextDoseDecision.PROCEED
    assert cycle.next_dose.decision_support_only is True

    # 6. It all persisted together.
    stored = rig["repo"].get_cycle(cycle.cycle_id)
    assert stored is not None
    assert stored.next_dose.decision is NextDoseDecision.PROCEED
    assert stored.state.patient_id == patient_id


def test_review_required_patient_enters_phase_two_with_an_override(rig):
    """The flagship demo record (P-1042) is REVIEW_REQUIRED, not ELIGIBLE."""
    screening = rig["screening"].screen(
        load_patient("patient_pdf_demo"), load_trial("trial_demo")
    )
    assert screening.overall_status is OverallStatus.REVIEW_REQUIRED

    treatment = rig["treatment"].register(
        screening_result_id=screening.result_id,
        drug_name="Compound X",
        now=START,
        override_by="Dr. Chen",
        override_reason="EXC-01 rule/AI disagreement reviewed.",
    )

    assert treatment.override.approved_by == "Dr. Chen"
    types = [e.event_type for e in rig["repo"].list_events(treatment.patient_id)]
    assert MonitoringEventType.ELIGIBILITY_OVERRIDE_RECORDED in types


# =========================================================================
# Trajectories through the full stack
# =========================================================================


def test_deterioration_escalates_and_holds_the_next_dose(rig):
    _, treatment = _register_eligible(rig)

    cycles = _drive(rig, treatment, Trajectory.GRADUAL_DETERIORATION)
    levels = _collapse([c.effective_risk.level for c in cycles])

    assert levels == [RiskLevel.GREEN, RiskLevel.AMBER, RiskLevel.RED]

    def interval(cycle):
        return next(
            i.monitoring_interval_minutes
            for i in cycle.interventions
            if i.monitoring_interval_minutes is not None
        )

    # Monitoring intensity increased along the way.
    assert interval(cycles[-1]) < interval(cycles[0])

    # A clinician was alerted, and the dose is held.
    assert any(
        i.action is InterventionAction.URGENT_ESCALATION
        for i in cycles[-1].interventions
    )
    assert cycles[-1].notifications
    assert cycles[-1].next_dose.decision is NextDoseDecision.HOLD


def test_recovery_de_escalates_and_returns_to_proceed(rig):
    _, treatment = _register_eligible(rig)

    cycles = _drive(rig, treatment, Trajectory.RECOVERY)
    levels = _collapse([c.effective_risk.level for c in cycles])

    assert levels == [RiskLevel.RED, RiskLevel.AMBER, RiskLevel.GREEN]
    assert cycles[0].next_dose.decision is NextDoseDecision.HOLD
    assert cycles[-1].next_dose.decision is NextDoseDecision.PROCEED


def test_failing_sensor_produces_unknown_not_a_reassuring_green(rig):
    """The trust gate's whole reason for existing."""
    _, treatment = _register_eligible(rig)

    cycles = _drive(rig, treatment, Trajectory.NOISY_SENSOR)
    final = cycles[-1]

    assert final.effective_risk.level is RiskLevel.UNKNOWN
    assert final.effective_risk.gated is True
    # The model's own opinion is retained, not erased.
    assert final.effective_risk.provider_level is RiskLevel.GREEN
    # And UNKNOWN demands more attention, not less.
    assert any(
        i.action is InterventionAction.REQUEST_REPEAT_OBSERVATION
        for i in final.interventions
    )
    assert final.next_dose.decision is not NextDoseDecision.PROCEED


def test_impossible_sensor_rows_are_rejected_and_reported(rig):
    _register_eligible(rig)
    batch = generate_windowed(
        "P-2006", "CT-001", Trajectory.NOISY_SENSOR, START, windows=1, hours=8, seed=7
    )[0]

    result = rig["ingestion"].ingest(batch, now=START)

    assert result.rejected_count > 0
    assert all(r.reason for r in result.rejected)


# =========================================================================
# Timeline and explainability
# =========================================================================


def test_the_timeline_records_the_whole_story_in_order(rig):
    _, treatment = _register_eligible(rig)
    rig["treatment"].record_dose(treatment.treatment_id, 5, "mg", now=START)

    _drive(rig, treatment, Trajectory.GRADUAL_DETERIORATION)

    events = rig["repo"].list_events(treatment.patient_id)
    types = [e.event_type for e in events]

    for expected in (
        MonitoringEventType.TREATMENT_REGISTERED,
        MonitoringEventType.DOSE_ADMINISTERED,
        MonitoringEventType.OBSERVATIONS_INGESTED,
        MonitoringEventType.RISK_ASSESSED,
        MonitoringEventType.RISK_TRANSITION,
        MonitoringEventType.INTERVENTION_RAISED,
        MonitoringEventType.NOTIFICATION_CREATED,
        MonitoringEventType.NEXT_DOSE_ASSESSED,
    ):
        assert expected in types, f"{expected.value} missing from the timeline"

    stamps = [e.occurred_at for e in events]
    assert stamps == sorted(stamps)


def test_every_decision_retains_its_inputs(rig):
    """A decision and the evidence for it are stored as one object."""
    _, treatment = _register_eligible(rig)
    cycles = _drive(rig, treatment, Trajectory.GRADUAL_DETERIORATION)
    final = cycles[-1]

    assert final.risk.contributing_factors
    assert all(i.evidence for i in final.interventions)
    assert final.next_dose.criteria
    assert final.next_dose.reasons
    assert final.state.measurements


def test_transitions_are_recorded_between_cycles(rig):
    _, treatment = _register_eligible(rig)
    cycles = _drive(rig, treatment, Trajectory.GRADUAL_DETERIORATION)

    transitions = [c.transition for c in cycles if c.transition]

    assert transitions[0].from_level is None  # first assessment
    assert any(
        t.from_level is RiskLevel.GREEN and t.to_level is RiskLevel.AMBER
        for t in transitions
    )


def test_repeat_cycles_without_new_data_report_no_transition(rig):
    _, treatment = _register_eligible(rig)
    batch = generate_windowed(
        treatment.patient_id, treatment.trial_id, Trajectory.STABLE, START,
        windows=1, hours=4, seed=5
    )[0]
    now = max(o.recorded_at for o in batch)
    rig["ingestion"].ingest(batch, now=now)

    first = rig["monitoring"].run_cycle(treatment.patient_id, treatment.trial_id, now)
    second = rig["monitoring"].run_cycle(treatment.patient_id, treatment.trial_id, now)

    assert first.transition is not None  # first ever assessment
    assert second.transition is None  # nothing changed


# =========================================================================
# Dashboard aggregate
# =========================================================================


def test_trial_overview_counts_patients_by_current_risk(rig):
    _, treatment = _register_eligible(rig)
    _drive(rig, treatment, Trajectory.GRADUAL_DETERIORATION)

    overview = rig["monitoring"].trial_overview(treatment.trial_id)

    assert overview["total_patients"] == 1
    assert overview["active_treatments"] == 1
    assert overview["risk_counts"]["RED"] == 1
    assert len(overview["requiring_attention"]) == 1
    assert overview["protocol_id"] == "DEMO-PROTOCOL-1"


def test_trial_overview_is_empty_before_any_treatment(rig):
    overview = rig["monitoring"].trial_overview("CT-001")

    assert overview["total_patients"] == 0
    assert overview["requiring_attention"] == []


# =========================================================================
# Phase 1 preservation
# =========================================================================


def test_phase_one_screening_is_unaffected_by_phase_two(rig):
    """Phase 2 activity must not disturb Phase 1 behaviour."""
    before = rig["screening"].screen(
        load_patient("patient_pdf_demo"), load_trial("trial_demo")
    )

    _, treatment = _register_eligible(rig)
    _drive(rig, treatment, Trajectory.GRADUAL_DETERIORATION)

    after = rig["screening"].screen(
        load_patient("patient_pdf_demo"), load_trial("trial_demo")
    )

    assert before.overall_status is after.overall_status
    assert before.rule_coverage == after.rule_coverage
    assert [r.status for r in before.criteria_results] == [
        r.status for r in after.criteria_results
    ]
    assert len(before.disagreements) == len(after.disagreements)
