from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel


class XAIExplanationRequest(BaseModel):
    """Payload sent by the UI to request an AI interpretation of a risk state."""
    model_name: str
    model_version: str
    signal_type: str
    risk_state: str
    score: float | None = None
    score_semantics: str
    horizon_hours: int | None = None
    evidence: list[dict[str, Any]]
    deterministic_explanation: str | None = None


class XAIExplanation(BaseModel):
    """The narrative output generated by the XAI layer."""
    explanation_text: str
    evidence_references: list[str]
    generated_at: datetime
    model_name: str = "gemini-3.1-pro"
    prompt_version: str = "v1.0"
    status: str
