"""whatsapp session support: approval session_active, incoming from_address

Revision ID: 4caba4bb846e
Revises: 7746dd0c9a43
Create Date: 2026-09-07 09:06:29.667129
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4caba4bb846e'
down_revision: Union[str, None] = '7746dd0c9a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_records', sa.Column('session_active', sa.Boolean(), server_default='false', nullable=False), schema='trialguard')
    op.add_column('incoming_messages', sa.Column('from_address', sa.String(), nullable=True), schema='trialguard')
    op.create_index('ix_incoming_messages_channel_from_received', 'incoming_messages', ['channel', 'from_address', 'received_at'], unique=False, schema='trialguard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incoming_messages_channel_from_received', table_name='incoming_messages', schema='trialguard')
    op.drop_column('incoming_messages', 'from_address', schema='trialguard')
    op.drop_column('approval_records', 'session_active', schema='trialguard')
    # ### end Alembic commands ###
