"""obligation layer: parties, obligations, actions, proposals, approvals

Revision ID: 6c19d78a2d9e
Revises: e003f38e8ee6
Create Date: 2026-09-06 21:49:03.737533
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c19d78a2d9e'
down_revision: Union[str, None] = 'e003f38e8ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible_parties',
    sa.Column('party_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('preferred_channel', sa.String(), server_default='IN_APP', nullable=False),
    sa.Column('trial_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('party_id'),
    schema='trialguard'
    )
    op.create_table('obligations',
    sa.Column('obligation_id', sa.String(), nullable=False),
    sa.Column('obligation_key', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('requirement_ref', sa.String(), nullable=False),
    sa.Column('requirement_text', sa.String(), nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('detector_source', sa.String(), nullable=False),
    sa.Column('occurrence', sa.String(), server_default='', nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsible_party_id', sa.String(), nullable=True),
    sa.Column('escalation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('action_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_kind', sa.String(), nullable=True),
    sa.Column('resolution_by', sa.String(), nullable=True),
    sa.Column('resolution_note', sa.String(), nullable=True),
    sa.Column('resolution_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status IN ('OPEN','AWAITING_RESPONSE') AND resolved_at IS NULL AND resolution_kind IS NULL) OR (status IN ('RESOLVED','DISMISSED') AND resolved_at IS NOT NULL AND resolution_kind IS NOT NULL AND resolution_by IS NOT NULL AND resolution_note IS NOT NULL)", name='ck_obligation_terminal_has_resolution'),
    sa.ForeignKeyConstraint(['responsible_party_id'], ['trialguard.responsible_parties.party_id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('obligation_id'),
    schema='trialguard'
    )
    op.create_index('obligations_active_key', 'obligations', ['obligation_key'], unique=True, schema='trialguard', postgresql_where=sa.text("status IN ('OPEN', 'AWAITING_RESPONSE')"))
    op.create_index('obligations_party', 'obligations', ['responsible_party_id'], unique=False, schema='trialguard')
    op.create_index('obligations_queue', 'obligations', ['trial_id', 'status', 'priority', 'first_detected_at'], unique=False, schema='trialguard')
    op.create_index('obligations_scope', 'obligations', ['trial_id', 'patient_id', 'detector_source'], unique=False, schema='trialguard')
    op.create_table('proposed_actions',
    sa.Column('proposal_id', sa.String(), nullable=False),
    sa.Column('obligation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('patient_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recipient_party_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('template_params', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prov_generated_by', sa.String(), nullable=False),
    sa.Column('prov_provider_kind', sa.String(), nullable=False),
    sa.Column('prov_model_name', sa.String(), nullable=True),
    sa.Column('prov_prompt_version', sa.String(), nullable=True),
    sa.Column('prov_latency_ms', sa.Integer(), nullable=True),
    sa.Column('prov_degraded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('prov_tools_called', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('prov_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('prov_unresolved', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('dec_outcome', sa.String(), nullable=True),
    sa.Column('dec_reviewer', sa.String(), nullable=True),
    sa.Column('dec_note', sa.String(), nullable=True),
    sa.Column('dec_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dec_edited_subject', sa.String(), nullable=True),
    sa.Column('dec_edited_body', sa.String(), nullable=True),
    sa.Column('exec_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exec_provider', sa.String(), nullable=True),
    sa.Column('exec_channel', sa.String(), nullable=True),
    sa.Column('exec_notification_id', sa.String(), nullable=True),
    sa.Column('exec_provider_message_id', sa.String(), nullable=True),
    sa.Column('exec_provider_thread_id', sa.String(), nullable=True),
    sa.Column('exec_delivery_status', sa.String(), nullable=True),
    sa.Column('exec_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('proposal_id'),
    schema='trialguard'
    )
    op.create_index('ix_proposed_actions_recipient', 'proposed_actions', ['recipient_party_id'], unique=False, schema='trialguard')
    op.create_index('ix_proposed_actions_status_created', 'proposed_actions', ['status', 'created_at'], unique=False, schema='trialguard')
    op.create_table('approval_records',
    sa.Column('proposal_id', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('template_params', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['trialguard.proposed_actions.proposal_id'], ),
    sa.PrimaryKeyConstraint('proposal_id'),
    schema='trialguard'
    )
    op.create_table('obligation_actions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('obligation_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_kind', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('recipient_party_id', sa.String(), nullable=True),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('note', sa.String(), server_default='', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint("(actor_kind = 'RESEARCHER' AND actor_name IS NOT NULL AND actor_name <> '') OR (actor_kind <> 'RESEARCHER' AND actor_name IS NULL)", name='researcher_is_named'),
    sa.ForeignKeyConstraint(['obligation_id'], ['trialguard.obligations.obligation_id'], ),
    sa.ForeignKeyConstraint(['recipient_party_id'], ['trialguard.responsible_parties.party_id'], ),
    sa.PrimaryKeyConstraint('action_id'),
    sa.UniqueConstraint('obligation_id', 'seq', name='ledger_order'),
    schema='trialguard'
    )
    op.create_index('ix_obligation_actions_obligation_seq', 'obligation_actions', ['obligation_id', 'seq'], unique=False, schema='trialguard')
    op.add_column('notifications', sa.Column('proposal_id', sa.String(), nullable=True), schema='trialguard')
    op.create_foreign_key('fk_notifications_proposal_id', 'notifications', 'proposed_actions', ['proposal_id'], ['proposal_id'], source_schema='trialguard', referent_schema='trialguard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_proposal_id', 'notifications', schema='trialguard', type_='foreignkey')
    op.drop_column('notifications', 'proposal_id', schema='trialguard')
    op.drop_index('ix_obligation_actions_obligation_seq', table_name='obligation_actions', schema='trialguard')
    op.drop_table('obligation_actions', schema='trialguard')
    op.drop_table('approval_records', schema='trialguard')
    op.drop_index('ix_proposed_actions_status_created', table_name='proposed_actions', schema='trialguard')
    op.drop_index('ix_proposed_actions_recipient', table_name='proposed_actions', schema='trialguard')
    op.drop_table('proposed_actions', schema='trialguard')
    op.drop_index('obligations_scope', table_name='obligations', schema='trialguard')
    op.drop_index('obligations_queue', table_name='obligations', schema='trialguard')
    op.drop_index('obligations_party', table_name='obligations', schema='trialguard')
    op.drop_index('obligations_active_key', table_name='obligations', schema='trialguard', postgresql_where=sa.text("status IN ('OPEN', 'AWAITING_RESPONSE')"))
    op.drop_table('obligations', schema='trialguard')
    op.drop_table('responsible_parties', schema='trialguard')
    # ### end Alembic commands ###
