"""approval recipient contact fields, incoming messages

Revision ID: 7746dd0c9a43
Revises: 6c19d78a2d9e
Create Date: 2026-09-07 01:40:19.400114
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7746dd0c9a43'
down_revision: Union[str, None] = '6c19d78a2d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=False),
    sa.Column('provider_thread_id', sa.String(), nullable=True),
    sa.Column('from_party_id', sa.String(), nullable=True),
    sa.Column('obligation_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_text', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['from_party_id'], ['trialguard.responsible_parties.party_id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['trialguard.obligations.obligation_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('channel', 'provider_message_id', name='inbound_idempotent'),
    schema='trialguard'
    )
    op.create_index('ix_incoming_messages_obligation', 'incoming_messages', ['obligation_id'], unique=False, schema='trialguard')
    op.create_index('ix_incoming_messages_thread', 'incoming_messages', ['provider_thread_id'], unique=False, schema='trialguard')
    op.add_column('approval_records', sa.Column('recipient_email', sa.String(), nullable=True), schema='trialguard')
    op.add_column('approval_records', sa.Column('recipient_phone', sa.String(), nullable=True), schema='trialguard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_records', 'recipient_phone', schema='trialguard')
    op.drop_column('approval_records', 'recipient_email', schema='trialguard')
    op.drop_index('ix_incoming_messages_thread', table_name='incoming_messages', schema='trialguard')
    op.drop_index('ix_incoming_messages_obligation', table_name='incoming_messages', schema='trialguard')
    op.drop_table('incoming_messages', schema='trialguard')
    # ### end Alembic commands ###
