"""initial schema: group A and B tables

Revision ID: e003f38e8ee6
Revises: 
Create Date: 2026-09-06 20:53:03.424301
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e003f38e8ee6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('patient_id'),
    schema='trialguard'
    )
    op.create_table('trials',
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('trial_id'),
    schema='trialguard'
    )
    op.create_table('adverse_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('onset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    schema='trialguard'
    )
    op.create_index('ix_adverse_events_patient_onset', 'adverse_events', ['patient_id', 'onset_at'], unique=False, schema='trialguard')
    op.create_table('monitoring_cycles',
    sa.Column('cycle_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('cycle_id'),
    schema='trialguard'
    )
    op.create_index('ix_monitoring_cycles_patient_generated', 'monitoring_cycles', ['patient_id', 'generated_at'], unique=False, schema='trialguard')
    op.create_table('monitoring_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    schema='trialguard'
    )
    op.create_index('ix_monitoring_events_patient_occurred', 'monitoring_events', ['patient_id', 'occurred_at'], unique=False, schema='trialguard')
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('notification_id'),
    schema='trialguard'
    )
    op.create_index('ix_notifications_patient_created', 'notifications', ['patient_id', 'created_at'], unique=False, schema='trialguard')
    op.create_table('observations',
    sa.Column('observation_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('measurement_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('quality_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('observation_id'),
    schema='trialguard'
    )
    op.create_index('ix_observations_patient_recorded', 'observations', ['patient_id', 'recorded_at'], unique=False, schema='trialguard')
    op.create_index('ix_observations_patient_type_recorded', 'observations', ['patient_id', 'measurement_type', 'recorded_at'], unique=False, schema='trialguard')
    op.create_table('screening_results',
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['trialguard.patients.patient_id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    schema='trialguard'
    )
    op.create_index('ix_screening_results_patient_trial_generated', 'screening_results', ['patient_id', 'trial_id', 'generated_at'], unique=False, schema='trialguard')
    op.create_table('treatments',
    sa.Column('treatment_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('screening_result_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['screening_result_id'], ['trialguard.screening_results.result_id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trialguard.trials.trial_id'], ),
    sa.PrimaryKeyConstraint('treatment_id'),
    schema='trialguard'
    )
    op.create_index('ix_treatments_patient', 'treatments', ['patient_id'], unique=False, schema='trialguard')
    op.create_index('ix_treatments_trial_status', 'treatments', ['trial_id', 'status'], unique=False, schema='trialguard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_treatments_trial_status', table_name='treatments', schema='trialguard')
    op.drop_index('ix_treatments_patient', table_name='treatments', schema='trialguard')
    op.drop_table('treatments', schema='trialguard')
    op.drop_index('ix_screening_results_patient_trial_generated', table_name='screening_results', schema='trialguard')
    op.drop_table('screening_results', schema='trialguard')
    op.drop_index('ix_observations_patient_type_recorded', table_name='observations', schema='trialguard')
    op.drop_index('ix_observations_patient_recorded', table_name='observations', schema='trialguard')
    op.drop_table('observations', schema='trialguard')
    op.drop_index('ix_notifications_patient_created', table_name='notifications', schema='trialguard')
    op.drop_table('notifications', schema='trialguard')
    op.drop_index('ix_monitoring_events_patient_occurred', table_name='monitoring_events', schema='trialguard')
    op.drop_table('monitoring_events', schema='trialguard')
    op.drop_index('ix_monitoring_cycles_patient_generated', table_name='monitoring_cycles', schema='trialguard')
    op.drop_table('monitoring_cycles', schema='trialguard')
    op.drop_index('ix_adverse_events_patient_onset', table_name='adverse_events', schema='trialguard')
    op.drop_table('adverse_events', schema='trialguard')
    op.drop_table('trials', schema='trialguard')
    op.drop_table('patients', schema='trialguard')
    # ### end Alembic commands ###
